project_name: "FaceQuant-Robustness"
version: "0.1.0"

system:
  seed: 42
  device_train: "cuda"
  device_inference: "cpu"
  num_workers: 4

data:
  dataset_name: "CASIA-WebFace"
  data_root: "./data"
  train_batch_size: 64  # Ajustado para 8GB VRAM
  val_batch_size: 64
  input_size: [112, 112] # Estandar InsightFace / ArcFace

models:
  backbones:
    - "mobilenet_v3_small"
    - "resnet18"
  embedding_size: 512
  pretrained: true

quantization:
  backend: "fbgemm" # x86 CPU standard
  method: "post_training_static" # PTQ
  calibration_steps: 100

training:
  epochs: 20
  learning_rate: 0.001
  optimizer: "adamw"
  weight_decay: 1e-4
